import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Button from '../components/Button'
import Input from '../components/Input'
import Title from '../components/Title'
import styles from '../styles/Home.module.css'

const resist = () => {
  console.log('resist');
  
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-[#fafafa] h-full max-w-5xl mx-auto flex flex-col justify-center p-4 text-gray-800'>

        <Title>登録情報</Title>

        <Input>ID</Input>
        <Input>PASS</Input>

        <div className='mx-auto mt-4'>
          <Button name='登録' clickButton={resist}></Button>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
